# Generated by Django 4.2.5 on 2023-10-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proname', models.CharField(max_length=50)),
                ('Prodescription', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ProCost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ProCreated', models.DateTimeField()),
            ],
        ),
    ]
