# Generated by Django 4.2.5 on 2023-10-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_product_prodescription_remove_product_proname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProDescription',
            new_name='Prodescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProName',
            new_name='Proname',
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanALTERNATIVES', models.ManyToManyField(related_name='alternative_product', to='ecommerce.product')),
                ('PlanProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'product alternatives',
                'verbose_name_plural': 'product alternatives',
            },
        ),
        migrations.CreateModel(
            name='CategProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatMain_category', models.CharField(max_length=40)),
                ('CatDescription', models.TextField()),
                ('CatImage', models.ImageField(upload_to='proImages/%y/%m/%d', verbose_name='image category ')),
                ('CatParent', models.ForeignKey(blank=True, limit_choices_to={'CatParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categprod')),
            ],
            options={
                'verbose_name': 'categories',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Procategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categprod'),
        ),
    ]
