# Generated by Django 4.2.5 on 2023-10-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('ecommerce', '0004_product_accessoires'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProdBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand'),
        ),
    ]
