# Generated by Django 4.2.5 on 2023-10-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_product_proimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proSlug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
